export const productSuggestions = {
  Grocery: [
    { name: "India Gate Basmati Rice", category: "Grocery", description: "Premium aged basmati rice", purchase: 85, selling: 110, stockQty: 25, inWeight: true, weightUnit: "kg", weight: 1 },
    { name: "Tata Sugar", category: "Grocery", description: "Double refined crystal sugar", purchase: 42, selling: 52, stockQty: 20, inWeight: true, weightUnit: "kg", weight: 1 },
    { name: "Tata Salt", category: "Grocery", description: "Vacuum evaporated iodized salt", purchase: 18, selling: 24, stockQty: 30, inWeight: true, weightUnit: "kg", weight: 1 },
    { name: "Aashirvaad Atta", category: "Grocery", description: "Whole wheat chakki fresh atta", purchase: 58, selling: 72, stockQty: 15, inWeight: true, weightUnit: "kg", weight: 5 },
    { name: "Fortune Sunflower Oil", category: "Grocery", description: "Refined sunflower cooking oil", purchase: 135, selling: 155, stockQty: 18, inWeight: true, weightUnit: "liter", weight: 1 },
    { name: "Tata Tea Gold", category: "Grocery", description: "Premium blended leaf tea", purchase: 225, selling: 265, stockQty: 8, inWeight: true, weightUnit: "kg", weight: 0.5 },
    { name: "Nescafe Classic", category: "Grocery", description: "Instant coffee powder", purchase: 195, selling: 245, stockQty: 10, inWeight: true, weightUnit: "gram", weight: 100 },
    { name: "Amul Butter", category: "Grocery", description: "Pasteurized table butter", purchase: 52, selling: 62, stockQty: 20, inWeight: true, weightUnit: "gram", weight: 100 },
    { name: "Britannia Marie Gold", category: "Grocery", description: "Light crispy biscuits", purchase: 8, selling: 12, stockQty: 40, inWeight: false, weightUnit: "pack", weight: 0 },
    { name: "Parle-G Biscuits", category: "Grocery", description: "Glucose biscuits family pack", purchase: 10, selling: 14, stockQty: 50, inWeight: false, weightUnit: "pack", weight: 0 },
    { name: "Maggi Noodles", category: "Grocery", description: "2-minute masala noodles", purchase: 12, selling: 16, stockQty: 60, inWeight: false, weightUnit: "pack", weight: 0 },
    { name: "Amul Taaza Milk", category: "Grocery", description: "Homogenized toned milk", purchase: 24, selling: 30, stockQty: 35, inWeight: true, weightUnit: "liter", weight: 1 },
    { name: "Saffola Gold Oil", category: "Grocery", description: "Blended edible oil heart care", purchase: 155, selling: 185, stockQty: 12, inWeight: true, weightUnit: "liter", weight: 1 },
    { name: "MDH Garam Masala", category: "Grocery", description: "Blended aromatic spice mix", purchase: 48, selling: 65, stockQty: 20, inWeight: true, weightUnit: "gram", weight: 100 },
    { name: "Everest Chilli Powder", category: "Grocery", description: "Pure red chilli powder", purchase: 38, selling: 52, stockQty: 18, inWeight: true, weightUnit: "gram", weight: 100 },
    { name: "Dawat Brown Rice", category: "Grocery", description: "Whole grain brown basmati", purchase: 95, selling: 125, stockQty: 10, inWeight: true, weightUnit: "kg", weight: 1 },
    { name: "Horlicks Original", category: "Grocery", description: "Health and nutrition drink", purchase: 185, selling: 235, stockQty: 14, inWeight: true, weightUnit: "gram", weight: 500 },
    { name: "Kissan Mixed Fruit Jam", category: "Grocery", description: "Mixed fruit preserve spread", purchase: 72, selling: 95, stockQty: 16, inWeight: true, weightUnit: "gram", weight: 200 },
  ],

  Stationery: [
    { name: "Classmate Notebook", category: "Stationery", description: "Single line ruled 180 pages", purchase: 38, selling: 52, stockQty: 50, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Reynolds 045 Pen", category: "Stationery", description: "Fine ball point blue pen", purchase: 6, selling: 12, stockQty: 100, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Natraj HB Pencil", category: "Stationery", description: "Break resistant graphite pencil", purchase: 3, selling: 6, stockQty: 80, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Camlin Marker", category: "Stationery", description: "Permanent waterproof marker", purchase: 15, selling: 25, stockQty: 28, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Apsara Eraser", category: "Stationery", description: "Non-smudge soft rubber eraser", purchase: 3, selling: 6, stockQty: 60, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Faber-Castell Sharpener", category: "Stationery", description: "Dual hole metal sharpener", purchase: 8, selling: 18, stockQty: 45, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Camlin Geometry Box", category: "Stationery", description: "9-piece student geometry set", purchase: 58, selling: 90, stockQty: 15, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Lexi Exam Pad", category: "Stationery", description: "Hard board writing exam pad", purchase: 22, selling: 38, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Scotch Tape", category: "Stationery", description: "Transparent adhesive tape roll", purchase: 12, selling: 22, stockQty: 30, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Fevicol Glue Stick", category: "Stationery", description: "Non-toxic washable glue stick", purchase: 12, selling: 22, stockQty: 22, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Camlin Sketch Pens", category: "Stationery", description: "24 shade colour sketch pens", purchase: 35, selling: 55, stockQty: 16, inWeight: false, weightUnit: "pack", weight: 0 },
    { name: "Solo File Folder", category: "Stationery", description: "Polypropylene transparent folder", purchase: 20, selling: 35, stockQty: 25, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Stapler Kokuyo", category: "Stationery", description: "Heavy duty 24/6 stapler", purchase: 85, selling: 130, stockQty: 12, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Faber-Castell Colour Pencils", category: "Stationery", description: "12 shade pre-sharpened pencils", purchase: 42, selling: 68, stockQty: 18, inWeight: false, weightUnit: "pack", weight: 0 },
  ],

  Medical: [
    { name: "Crocin Advance", category: "Medical", description: "Paracetamol 500mg fever relief", purchase: 28, selling: 42, stockQty: 40, inWeight: false, weightUnit: "strip", weight: 0 },
    { name: "Benadryl Cough Syrup", category: "Medical", description: "Dry cough relief 100ml", purchase: 85, selling: 120, stockQty: 18, inWeight: true, weightUnit: "ml", weight: 100 },
    { name: "Band-Aid Strips", category: "Medical", description: "Flexible fabric bandage strips", purchase: 38, selling: 58, stockQty: 25, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Dettol Hand Sanitizer", category: "Medical", description: "Kills 99.9% germs 100ml", purchase: 52, selling: 75, stockQty: 20, inWeight: true, weightUnit: "ml", weight: 100 },
    { name: "3M Surgical Mask", category: "Medical", description: "3-layer fluid resistant mask", purchase: 6, selling: 12, stockQty: 120, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Dr. Morepen Thermometer", category: "Medical", description: "Digital clinical thermometer", purchase: 145, selling: 210, stockQty: 10, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Omron BP Monitor", category: "Medical", description: "Automatic upper arm monitor", purchase: 1200, selling: 1650, stockQty: 4, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Volini Pain Relief Spray", category: "Medical", description: "Diclofenac muscle pain spray", purchase: 135, selling: 190, stockQty: 15, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "ORS Electral Powder", category: "Medical", description: "Oral rehydration salts sachet", purchase: 12, selling: 20, stockQty: 50, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Betadine Antiseptic", category: "Medical", description: "Povidone iodine wound solution", purchase: 75, selling: 110, stockQty: 12, inWeight: true, weightUnit: "ml", weight: 100 },
  ],

  Electronics: [
    { name: "Anker 20W USB-C Charger", category: "Electronics", description: "PowerIQ fast wall charger", purchase: 380, selling: 599, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "boAt Type-C Cable", category: "Electronics", description: "Tangle-free braided 2m cable", purchase: 95, selling: 199, stockQty: 30, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "boAt BassHeads Earphones", category: "Electronics", description: "Super extra bass wired earphones", purchase: 180, selling: 349, stockQty: 22, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "JBL Go 3 Speaker", category: "Electronics", description: "Portable waterproof bluetooth speaker", purchase: 1200, selling: 1999, stockQty: 8, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Mi 10000mAh Power Bank", category: "Electronics", description: "18W fast charge slim powerbank", purchase: 850, selling: 1299, stockQty: 6, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Zebronics USB Keyboard", category: "Electronics", description: "Multimedia wired keyboard", purchase: 380, selling: 599, stockQty: 10, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Logitech M90 Mouse", category: "Electronics", description: "Optical ambidextrous wired mouse", purchase: 280, selling: 449, stockQty: 15, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "TP-Link Wi-Fi Router", category: "Electronics", description: "300Mbps wireless N router", purchase: 850, selling: 1299, stockQty: 8, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Syska LED Bulb 9W", category: "Electronics", description: "Energy saving cool white bulb", purchase: 52, selling: 89, stockQty: 40, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Havells Extension Board", category: "Electronics", description: "4 socket surge protector 1.5m", purchase: 280, selling: 449, stockQty: 12, inWeight: false, weightUnit: "piece", weight: 0 },
  ],

  Clothing: [
    { name: "Jockey Cotton T-Shirt", category: "Clothing", description: "Regular fit solid round neck", purchase: 280, selling: 499, stockQty: 25, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Arrow Formal Shirt", category: "Clothing", description: "Full sleeve easy iron shirt", purchase: 580, selling: 999, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Levi's 511 Jeans", category: "Clothing", description: "Slim fit mid-rise stretch jeans", purchase: 1200, selling: 2199, stockQty: 16, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Biba Printed Kurti", category: "Clothing", description: "Cotton straight printed kurti", purchase: 480, selling: 899, stockQty: 12, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Jockey Leggings", category: "Clothing", description: "Cotton stretch ankle length", purchase: 320, selling: 599, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Van Heusen Polo Shirt", category: "Clothing", description: "Regular fit pique polo", purchase: 480, selling: 899, stockQty: 14, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Peter England Trouser", category: "Clothing", description: "Slim fit formal trouser", purchase: 680, selling: 1299, stockQty: 10, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Dollar Innerwear Vest", category: "Clothing", description: "Cotton ribbed sleeveless vest", purchase: 95, selling: 185, stockQty: 30, inWeight: false, weightUnit: "piece", weight: 0 },
  ],

  Footwear: [
    { name: "Nike Revolution Running Shoes", category: "Footwear", description: "Lightweight mesh running shoes", purchase: 1800, selling: 3299, stockQty: 20, inWeight: false, weightUnit: "pair", weight: 0 },
    { name: "Bata Casual Sandals", category: "Footwear", description: "Comfort foam padded sandals", purchase: 480, selling: 899, stockQty: 18, inWeight: false, weightUnit: "pair", weight: 0 },
    { name: "Paragon Slippers", category: "Footwear", description: "Extra soft rubber flip flops", purchase: 95, selling: 199, stockQty: 30, inWeight: false, weightUnit: "pair", weight: 0 },
    { name: "Red Chief Formal Shoes", category: "Footwear", description: "Genuine leather lace-up shoes", purchase: 1400, selling: 2499, stockQty: 12, inWeight: false, weightUnit: "pair", weight: 0 },
    { name: "Liberty School Shoes", category: "Footwear", description: "Black leather school shoes", purchase: 520, selling: 950, stockQty: 15, inWeight: false, weightUnit: "pair", weight: 0 },
    { name: "Adidas Adilette Slides", category: "Footwear", description: "Cloudfoam pool slides", purchase: 680, selling: 1299, stockQty: 10, inWeight: false, weightUnit: "pair", weight: 0 },
    { name: "Woodland Trekking Shoes", category: "Footwear", description: "Water resistant hiking shoes", purchase: 1800, selling: 3199, stockQty: 8, inWeight: false, weightUnit: "pair", weight: 0 },
  ],

  Jewelry: [
    { name: "Tanishq 22K Gold Ring", category: "Jewelry", description: "Hallmarked 22K gold finger ring", purchase: 22000, selling: 28000, stockQty: 5, inWeight: true, weightUnit: "gram", weight: 5 },
    { name: "PC Jeweller Silver Chain", category: "Jewelry", description: "925 pure silver chain 20 inch", purchase: 1800, selling: 2499, stockQty: 10, inWeight: true, weightUnit: "gram", weight: 20 },
    { name: "Mia Diamond Earrings", category: "Jewelry", description: "14K gold diamond stud earrings", purchase: 18000, selling: 26000, stockQty: 4, inWeight: false, weightUnit: "pair", weight: 0 },
    { name: "Tanishq Gold Necklace", category: "Jewelry", description: "Traditional 22K temple necklace", purchase: 52000, selling: 65000, stockQty: 3, inWeight: true, weightUnit: "gram", weight: 40 },
    { name: "Shaya Silver Anklet", category: "Jewelry", description: "Sterling silver payal anklet", purchase: 850, selling: 1299, stockQty: 12, inWeight: true, weightUnit: "gram", weight: 30 },
    { name: "Zaveri Pearls Bracelet", category: "Jewelry", description: "Rhodium plated charm bracelet", purchase: 380, selling: 699, stockQty: 15, inWeight: false, weightUnit: "piece", weight: 0 },
  ],

  Hardware: [
    { name: "Stanley Claw Hammer", category: "Hardware", description: "16oz fibreglass handle hammer", purchase: 380, selling: 599, stockQty: 25, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Stanley Screwdriver Set", category: "Hardware", description: "6-piece insulated screwdriver set", purchase: 280, selling: 449, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Taparia Iron Nails", category: "Hardware", description: "Bright wire iron nails pack", purchase: 45, selling: 75, stockQty: 50, inWeight: true, weightUnit: "kg", weight: 1 },
    { name: "Bosch Drill Machine", category: "Hardware", description: "500W corded electric drill", purchase: 2200, selling: 3499, stockQty: 8, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Taparia Adjustable Wrench", category: "Hardware", description: "Drop forged steel wrench 12\"", purchase: 320, selling: 520, stockQty: 18, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Fevikwik Instant Adhesive", category: "Hardware", description: "Cyanoacrylate super glue 5g", purchase: 18, selling: 35, stockQty: 40, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Anchor Electrical Wire", category: "Hardware", description: "1.5 sq mm FR PVC wire 90m", purchase: 1800, selling: 2699, stockQty: 6, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Pidilite M-Seal", category: "Hardware", description: "Epoxy compound 50g all purpose", purchase: 48, selling: 80, stockQty: 30, inWeight: false, weightUnit: "piece", weight: 0 },
  ],

  Furniture: [
    { name: "Nilkamal Plastic Chair", category: "Furniture", description: "Stackable premium plastic chair", purchase: 680, selling: 1099, stockQty: 10, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Durian Dining Table", category: "Furniture", description: "Solid wood 6-seater dining set", purchase: 22000, selling: 34999, stockQty: 3, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Godrej Interio Office Desk", category: "Furniture", description: "Steel frame laminate top desk", purchase: 8500, selling: 13999, stockQty: 5, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Wakefit Sofa Set 3+1+1", category: "Furniture", description: "Fabric upholstered sofa set", purchase: 28000, selling: 44999, stockQty: 2, inWeight: false, weightUnit: "set", weight: 0 },
    { name: "Pepperfry Queen Bed Frame", category: "Furniture", description: "Solid sheesham wood queen bed", purchase: 18000, selling: 27999, stockQty: 3, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Godrej Interio Wardrobe", category: "Furniture", description: "3-door steel almirah with mirror", purchase: 12000, selling: 18999, stockQty: 4, inWeight: false, weightUnit: "piece", weight: 0 },
  ],

  Cosmetic: [
    { name: "Lakme Face Cream", category: "Cosmetic", description: "Sun expert SPF 24 moisturizer", purchase: 145, selling: 225, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Maybelline Lipstick", category: "Cosmetic", description: "Color sensational matte lipstick", purchase: 195, selling: 325, stockQty: 25, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Himalaya Face Wash", category: "Cosmetic", description: "Neem purifying face wash 100ml", purchase: 88, selling: 135, stockQty: 18, inWeight: true, weightUnit: "ml", weight: 100 },
    { name: "Skinn by Titan Perfume", category: "Cosmetic", description: "Celeste EDP 50ml for women", purchase: 580, selling: 995, stockQty: 12, inWeight: true, weightUnit: "ml", weight: 50 },
    { name: "Set Wet Hair Gel", category: "Cosmetic", description: "Vertical hold styling gel 250ml", purchase: 95, selling: 155, stockQty: 15, inWeight: true, weightUnit: "ml", weight: 250 },
    { name: "L'Oreal Shampoo", category: "Cosmetic", description: "6 oil nourish shampoo 175ml", purchase: 165, selling: 265, stockQty: 14, inWeight: true, weightUnit: "ml", weight: 175 },
    { name: "Nivea Body Lotion", category: "Cosmetic", description: "Soft smoothing moisturizer 200ml", purchase: 145, selling: 235, stockQty: 16, inWeight: true, weightUnit: "ml", weight: 200 },
    { name: "Dove Face Powder", category: "Cosmetic", description: "Translucent finishing loose powder", purchase: 185, selling: 299, stockQty: 10, inWeight: false, weightUnit: "piece", weight: 0 },
  ],

  "Book Store": [
    { name: "Chetan Bhagat - One Indian Girl", category: "Book Store", description: "Bestselling English fiction novel", purchase: 120, selling: 195, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Oxford English Dictionary", category: "Book Store", description: "Compact english dictionary", purchase: 380, selling: 599, stockQty: 10, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Arihant SSC CGL Guide", category: "Book Store", description: "Complete SSC exam preparation", purchase: 420, selling: 650, stockQty: 14, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Panchatantra Stories", category: "Book Store", description: "Illustrated children story book", purchase: 95, selling: 160, stockQty: 25, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "NCERT Science Class 10", category: "Book Store", description: "CBSE standard textbook", purchase: 68, selling: 110, stockQty: 30, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "R.D. Sharma Mathematics", category: "Book Store", description: "Class 12 maths reference book", purchase: 380, selling: 580, stockQty: 12, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Classmate Notebook Pack", category: "Book Store", description: "Pack of 6 single line notebooks", purchase: 145, selling: 225, stockQty: 20, inWeight: false, weightUnit: "pack", weight: 0 },
  ],

  "Mobile Shop": [
    { name: "Samsung Galaxy A15", category: "Mobile Shop", description: "6.5\" FHD+ 50MP 5000mAh phone", purchase: 12500, selling: 16999, stockQty: 10, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Spigen Mobile Cover", category: "Mobile Shop", description: "Rugged armor shockproof case", purchase: 180, selling: 399, stockQty: 60, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Gorilla Tempered Glass", category: "Mobile Shop", description: "9H hardness screen protector", purchase: 45, selling: 149, stockQty: 80, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Redmi Note 13", category: "Mobile Shop", description: "6.67\" AMOLED 108MP 5000mAh", purchase: 16500, selling: 21999, stockQty: 8, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "boAt Airdopes 141", category: "Mobile Shop", description: "TWS earbuds 42Hr playback", purchase: 850, selling: 1499, stockQty: 12, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Syska 20W Fast Charger", category: "Mobile Shop", description: "Type-C PD fast wall charger", purchase: 280, selling: 499, stockQty: 25, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Samsung 128GB Memory Card", category: "Mobile Shop", description: "EVO Plus microSDXC UHS-I", purchase: 480, selling: 799, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
  ],

  Bakery: [
    { name: "Britannia Bread Loaf", category: "Bakery", description: "Premium white sandwich bread", purchase: 38, selling: 55, stockQty: 30, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Monginis Chocolate Cake", category: "Bakery", description: "Moist dark chocolate layer cake", purchase: 380, selling: 599, stockQty: 10, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Butter Cookies", category: "Bakery", description: "Home style baked butter cookies", purchase: 160, selling: 250, stockQty: 20, inWeight: true, weightUnit: "kg", weight: 0.5 },
    { name: "Fresh Cream Pastry", category: "Bakery", description: "Whipped cream filled pastry", purchase: 45, selling: 80, stockQty: 25, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Glazed Chocolate Donut", category: "Bakery", description: "Soft ring donut with glaze", purchase: 28, selling: 55, stockQty: 30, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Croissant", category: "Bakery", description: "Flaky buttery french croissant", purchase: 35, selling: 65, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Pineapple Pastry", category: "Bakery", description: "Pineapple cream sponge pastry", purchase: 42, selling: 75, stockQty: 18, inWeight: false, weightUnit: "piece", weight: 0 },
  ],

  Restaurant: [
    { name: "Punjabi Veg Thali", category: "Restaurant", description: "Dal, sabzi, roti, rice, salad", purchase: 95, selling: 180, stockQty: 50, inWeight: false, weightUnit: "plate", weight: 0 },
    { name: "Paneer Butter Masala", category: "Restaurant", description: "Cottage cheese in rich tomato gravy", purchase: 140, selling: 260, stockQty: 30, inWeight: false, weightUnit: "plate", weight: 0 },
    { name: "Veg Dum Biryani", category: "Restaurant", description: "Aromatic basmati rice with veggies", purchase: 110, selling: 220, stockQty: 40, inWeight: false, weightUnit: "plate", weight: 0 },
    { name: "Butter Naan", category: "Restaurant", description: "Tandoor baked butter naan", purchase: 18, selling: 45, stockQty: 80, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Masala Chai", category: "Restaurant", description: "Ginger cardamom spiced tea", purchase: 8, selling: 20, stockQty: 100, inWeight: false, weightUnit: "cup", weight: 0 },
    { name: "Coca-Cola 300ml", category: "Restaurant", description: "Chilled cola soft drink bottle", purchase: 22, selling: 45, stockQty: 60, inWeight: false, weightUnit: "bottle", weight: 0 },
    { name: "Dal Makhani", category: "Restaurant", description: "Slow cooked black lentil curry", purchase: 120, selling: 230, stockQty: 35, inWeight: false, weightUnit: "plate", weight: 0 },
    { name: "Gulab Jamun", category: "Restaurant", description: "Soft khoya balls in sugar syrup", purchase: 25, selling: 60, stockQty: 50, inWeight: false, weightUnit: "plate", weight: 0 },
  ],

  "Gift Shop": [
    { name: "Archies Greeting Card", category: "Gift Shop", description: "Premium quality birthday card", purchase: 28, selling: 60, stockQty: 40, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Nikon Photo Frame", category: "Gift Shop", description: "Wooden 5x7 inch photo frame", purchase: 145, selling: 270, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Hamleys Teddy Bear", category: "Gift Shop", description: "Soft plush 30cm teddy bear", purchase: 280, selling: 499, stockQty: 15, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Hallmark Gift Box", category: "Gift Shop", description: "Decorative ribbon bow gift box", purchase: 80, selling: 160, stockQty: 25, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Engraved Metal Keychain", category: "Gift Shop", description: "Customizable steel keychain", purchase: 25, selling: 70, stockQty: 50, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Inorbit Flower Bouquet", category: "Gift Shop", description: "Fresh mix flower arrangement", purchase: 180, selling: 380, stockQty: 10, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Cadbury Celebration Box", category: "Gift Shop", description: "Assorted chocolate gift pack", purchase: 185, selling: 350, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
  ],

  "General Store": [
    { name: "Bharat Matches", category: "General Store", description: "Safety matchbox 50 sticks", purchase: 1, selling: 3, stockQty: 200, inWeight: false, weightUnit: "box", weight: 0 },
    { name: "Polybag Carry Bags", category: "General Store", description: "HDPE grocery carry bags pack", purchase: 38, selling: 65, stockQty: 50, inWeight: false, weightUnit: "pack", weight: 0 },
    { name: "Nilkamal Plastic Bucket", category: "General Store", description: "Heavy duty 20L plastic bucket", purchase: 95, selling: 165, stockQty: 18, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Milton Steel Mug", category: "General Store", description: "Stainless steel 350ml mug", purchase: 55, selling: 110, stockQty: 30, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Scotch Brite Floor Broom", category: "General Store", description: "Stiff bristle floor sweeping broom", purchase: 65, selling: 130, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Godrej Cinthol Soap", category: "General Store", description: "Deo soap germ protection 100g", purchase: 28, selling: 50, stockQty: 40, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Vim Dish Wash Bar", category: "General Store", description: "Lemon anti-bacterial dish bar", purchase: 18, selling: 35, stockQty: 35, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Harpic Toilet Cleaner", category: "General Store", description: "Power plus 10x cleaning 500ml", purchase: 85, selling: 150, stockQty: 15, inWeight: true, weightUnit: "ml", weight: 500 },
  ],

  "Sports Shop": [
    { name: "SS Ton Cricket Bat", category: "Sports Shop", description: "Kashmir willow full size bat", purchase: 780, selling: 1299, stockQty: 12, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "SG Cricket Ball", category: "Sports Shop", description: "Club leather cricket ball", purchase: 145, selling: 260, stockQty: 30, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Nivia Storm Football", category: "Sports Shop", description: "PVC machine stitched football", purchase: 480, selling: 799, stockQty: 10, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Yonex Badminton Racket", category: "Sports Shop", description: "GR-303 aluminum shaft racket", purchase: 380, selling: 650, stockQty: 16, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Cosco Skipping Rope", category: "Sports Shop", description: "PVC jump rope with foam handles", purchase: 75, selling: 149, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Adidas Sports Bag", category: "Sports Shop", description: "Polyester 30L gym duffel bag", purchase: 680, selling: 1199, stockQty: 8, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Nivia Volleyball", category: "Sports Shop", description: "Rubber moulded volleyball", purchase: 380, selling: 650, stockQty: 10, inWeight: false, weightUnit: "piece", weight: 0 },
  ],

  "Toy Shop": [
    { name: "Hot Wheels Toy Car", category: "Toy Shop", description: "Die-cast metal toy car 1:64", purchase: 85, selling: 175, stockQty: 40, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Barbie Fashion Doll", category: "Toy Shop", description: "Poseable doll with accessories", purchase: 380, selling: 699, stockQty: 25, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Funskool Puzzle 500pc", category: "Toy Shop", description: "Educational jigsaw puzzle", purchase: 195, selling: 380, stockQty: 18, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Lego Classic Blocks", category: "Toy Shop", description: "Creative building bricks 200pc", purchase: 580, selling: 1099, stockQty: 15, inWeight: false, weightUnit: "box", weight: 0 },
    { name: "Maisto RC Car", category: "Toy Shop", description: "1:18 remote control racing car", purchase: 650, selling: 1199, stockQty: 10, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Milton Water Gun", category: "Toy Shop", description: "High pressure water pistol", purchase: 85, selling: 175, stockQty: 20, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Hamleys Board Game", category: "Toy Shop", description: "Family strategy board game", purchase: 380, selling: 699, stockQty: 12, inWeight: false, weightUnit: "piece", weight: 0 },
  ],

  Agriculture: [
    { name: "Syngenta Wheat Seeds", category: "Agriculture", description: "High yield hybrid wheat seeds", purchase: 65, selling: 110, stockQty: 50, inWeight: true, weightUnit: "kg", weight: 1 },
    { name: "IFFCO Urea Fertilizer", category: "Agriculture", description: "Neem coated nitrogen fertilizer", purchase: 280, selling: 365, stockQty: 30, inWeight: true, weightUnit: "kg", weight: 50 },
    { name: "Bayer Confidor Pesticide", category: "Agriculture", description: "Systemic insecticide spray", purchase: 420, selling: 650, stockQty: 12, inWeight: true, weightUnit: "liter", weight: 1 },
    { name: "Kirloskar Water Pump", category: "Agriculture", description: "0.5HP self priming pump", purchase: 5200, selling: 8499, stockQty: 5, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Falcon Steel Shovel", category: "Agriculture", description: "Tempered steel blade spade", purchase: 320, selling: 550, stockQty: 14, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Coromandel DAP Fertilizer", category: "Agriculture", description: "Diammonium phosphate 50kg bag", purchase: 1380, selling: 1950, stockQty: 20, inWeight: true, weightUnit: "kg", weight: 50 },
    { name: "Mahindra Garden Sprayer", category: "Agriculture", description: "16L manual knapsack sprayer", purchase: 850, selling: 1399, stockQty: 8, inWeight: false, weightUnit: "piece", weight: 0 },
  ],

  Other: [
    { name: "Prestige Pressure Cooker", category: "Other", description: "Aluminium 5L pressure cooker", purchase: 850, selling: 1399, stockQty: 10, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Milton Water Bottle", category: "Other", description: "Stainless steel 1L hot & cold", purchase: 280, selling: 499, stockQty: 15, inWeight: false, weightUnit: "piece", weight: 0 },
    { name: "Cello Tape Dispenser", category: "Other", description: "Heavy duty desktop tape cutter", purchase: 145, selling: 250, stockQty: 8, inWeight: false, weightUnit: "piece", weight: 0 },
  ],
};