// SmartKhata product suggestion seed data
//
// IMPORTANT:
// - purchase/selling values are DEMO INR values.
// - Change prices according to your real wholesaler catalogue.
// - Keep product names consistent between wholesalers.
// - SmartKhata exact product matching depends on product name.

export const productSuggestions = {
  Grocery: [
    {
      name: "India Gate Basmati Rice",
      category: "Grocery",
      description: "Premium aged basmati rice",
      purchase: 85,
      selling: 110,
      stockQty: 25,
      inWeight: true,
      weightUnit: "kg",
      weight: 1,
    },
    {
      name: "Tata Sugar",
      category: "Grocery",
      description: "Double refined crystal sugar",
      purchase: 42,
      selling: 52,
      stockQty: 20,
      inWeight: true,
      weightUnit: "kg",
      weight: 1,
    },
    {
      name: "Tata Salt",
      category: "Grocery",
      description: "Vacuum evaporated iodized salt",
      purchase: 18,
      selling: 24,
      stockQty: 30,
      inWeight: true,
      weightUnit: "kg",
      weight: 1,
    },
    {
      name: "Aashirvaad Atta",
      category: "Grocery",
      description: "Whole wheat chakki fresh atta",
      purchase: 58,
      selling: 72,
      stockQty: 15,
      inWeight: true,
      weightUnit: "kg",
      weight: 5,
    },
    {
      name: "Fortune Sunflower Oil",
      category: "Grocery",
      description: "Refined sunflower cooking oil",
      purchase: 135,
      selling: 155,
      stockQty: 18,
      inWeight: true,
      weightUnit: "liter",
      weight: 1,
    },
    {
      name: "Tata Tea Gold",
      category: "Grocery",
      description: "Premium blended leaf tea",
      purchase: 225,
      selling: 265,
      stockQty: 8,
      inWeight: true,
      weightUnit: "kg",
      weight: 0.5,
    },
    {
      name: "Nescafe Classic",
      category: "Grocery",
      description: "Instant coffee powder",
      purchase: 195,
      selling: 245,
      stockQty: 10,
      inWeight: true,
      weightUnit: "gram",
      weight: 100,
    },
    {
      name: "Amul Butter",
      category: "Grocery",
      description: "Pasteurized table butter",
      purchase: 52,
      selling: 62,
      stockQty: 20,
      inWeight: true,
      weightUnit: "gram",
      weight: 100,
    },
    {
      name: "Britannia Marie Gold",
      category: "Grocery",
      description: "Light crispy biscuits",
      purchase: 8,
      selling: 12,
      stockQty: 40,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Parle-G Biscuits",
      category: "Grocery",
      description: "Glucose biscuits family pack",
      purchase: 10,
      selling: 14,
      stockQty: 50,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Maggi Noodles",
      category: "Grocery",
      description: "2-minute masala noodles",
      purchase: 12,
      selling: 16,
      stockQty: 60,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Amul Taaza Milk",
      category: "Grocery",
      description: "Homogenized toned milk",
      purchase: 24,
      selling: 30,
      stockQty: 35,
      inWeight: true,
      weightUnit: "liter",
      weight: 1,
    },
    {
      name: "Saffola Gold Oil",
      category: "Grocery",
      description: "Blended edible oil",
      purchase: 155,
      selling: 185,
      stockQty: 12,
      inWeight: true,
      weightUnit: "liter",
      weight: 1,
    },
    {
      name: "MDH Garam Masala",
      category: "Grocery",
      description: "Blended aromatic spice mix",
      purchase: 48,
      selling: 65,
      stockQty: 20,
      inWeight: true,
      weightUnit: "gram",
      weight: 100,
    },
    {
      name: "Everest Chilli Powder",
      category: "Grocery",
      description: "Pure red chilli powder",
      purchase: 38,
      selling: 52,
      stockQty: 18,
      inWeight: true,
      weightUnit: "gram",
      weight: 100,
    },
    {
      name: "Dawat Brown Rice",
      category: "Grocery",
      description: "Whole grain brown basmati",
      purchase: 95,
      selling: 125,
      stockQty: 10,
      inWeight: true,
      weightUnit: "kg",
      weight: 1,
    },
    {
      name: "Horlicks Original",
      category: "Grocery",
      description: "Health and nutrition drink",
      purchase: 185,
      selling: 235,
      stockQty: 14,
      inWeight: true,
      weightUnit: "gram",
      weight: 500,
    },
    {
      name: "Kissan Mixed Fruit Jam",
      category: "Grocery",
      description: "Mixed fruit preserve spread",
      purchase: 72,
      selling: 95,
      stockQty: 16,
      inWeight: true,
      weightUnit: "gram",
      weight: 200,
    },
    {
      name: "Tata Sampann Toor Dal",
      category: "Grocery",
      description: "Unpolished arhar dal for everyday Indian cooking",
      purchase: 145,
      selling: 165,
      stockQty: 25,
      inWeight: true,
      weightUnit: "kg",
      weight: 1,
    },
    {
      name: "Tata Sampann Chana Dal",
      category: "Grocery",
      description: "Protein-rich unpolished chana dal",
      purchase: 82,
      selling: 98,
      stockQty: 25,
      inWeight: true,
      weightUnit: "kg",
      weight: 1,
    },
    {
      name: "Fortune Besan",
      category: "Grocery",
      description: "Fine gram flour for snacks and cooking",
      purchase: 72,
      selling: 88,
      stockQty: 20,
      inWeight: true,
      weightUnit: "kg",
      weight: 1,
    },
    {
      name: "Amul Pure Ghee",
      category: "Grocery",
      description: "Dairy ghee for cooking and sweets",
      purchase: 565,
      selling: 635,
      stockQty: 12,
      inWeight: true,
      weightUnit: "liter",
      weight: 1,
    },
    {
      name: "Patanjali Poha",
      category: "Grocery",
      description: "Flattened rice for breakfast and snacks",
      purchase: 48,
      selling: 62,
      stockQty: 22,
      inWeight: true,
      weightUnit: "kg",
      weight: 1,
    },
    {
      name: "Fortune Groundnut Oil",
      category: "Grocery",
      description: "Refined groundnut cooking oil",
      purchase: 145,
      selling: 168,
      stockQty: 18,
      inWeight: true,
      weightUnit: "liter",
      weight: 1,
    },
    {
      name: "Surf Excel Matic Powder",
      category: "Grocery",
      description: "Machine wash detergent powder",
      purchase: 210,
      selling: 245,
      stockQty: 15,
      inWeight: true,
      weightUnit: "kg",
      weight: 1,
    },
    {
      name: "Haldirams Bhujia",
      category: "Grocery",
      description: "Classic Indian savoury namkeen",
      purchase: 185,
      selling: 220,
      stockQty: 18,
      inWeight: true,
      weightUnit: "gram",
      weight: 400,
    },
  ],

  Stationery: [
    {
      name: "Classmate Notebook",
      category: "Stationery",
      description: "Single line ruled 180 pages",
      purchase: 38,
      selling: 52,
      stockQty: 50,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Reynolds 045 Pen",
      category: "Stationery",
      description: "Fine ball point blue pen",
      purchase: 6,
      selling: 12,
      stockQty: 100,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Natraj HB Pencil",
      category: "Stationery",
      description: "Break resistant graphite pencil",
      purchase: 3,
      selling: 6,
      stockQty: 80,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Camlin Marker",
      category: "Stationery",
      description: "Permanent waterproof marker",
      purchase: 15,
      selling: 25,
      stockQty: 28,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Apsara Eraser",
      category: "Stationery",
      description: "Non-smudge soft rubber eraser",
      purchase: 3,
      selling: 6,
      stockQty: 60,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Faber-Castell Sharpener",
      category: "Stationery",
      description: "Dual hole metal sharpener",
      purchase: 8,
      selling: 18,
      stockQty: 45,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Camlin Geometry Box",
      category: "Stationery",
      description: "9-piece student geometry set",
      purchase: 58,
      selling: 90,
      stockQty: 15,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Lexi Exam Pad",
      category: "Stationery",
      description: "Hard board writing exam pad",
      purchase: 22,
      selling: 38,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Scotch Tape",
      category: "Stationery",
      description: "Transparent adhesive tape roll",
      purchase: 12,
      selling: 22,
      stockQty: 30,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Fevicol Glue Stick",
      category: "Stationery",
      description: "Non-toxic washable glue stick",
      purchase: 12,
      selling: 22,
      stockQty: 22,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Camlin Sketch Pens",
      category: "Stationery",
      description: "24 shade colour sketch pens",
      purchase: 35,
      selling: 55,
      stockQty: 16,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Solo File Folder",
      category: "Stationery",
      description: "Polypropylene transparent folder",
      purchase: 20,
      selling: 35,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Stapler Kokuyo",
      category: "Stationery",
      description: "Heavy duty 24/6 stapler",
      purchase: 85,
      selling: 130,
      stockQty: 12,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Faber-Castell Colour Pencils",
      category: "Stationery",
      description: "12 shade pre-sharpened pencils",
      purchase: 42,
      selling: 68,
      stockQty: 18,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "JK Copier A4 Paper Ream",
      category: "Stationery",
      description: "500-sheet A4 copier paper ream",
      purchase: 245,
      selling: 295,
      stockQty: 30,
      inWeight: false,
      weightUnit: "ream",
      weight: 0,
    },
    {
      name: "Classmate Long Register",
      category: "Stationery",
      description: "Hardbound ruled office and account register",
      purchase: 72,
      selling: 105,
      stockQty: 35,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Casio MJ-12D Calculator",
      category: "Stationery",
      description: "Desktop 12-digit calculator for shop billing",
      purchase: 410,
      selling: 525,
      stockQty: 15,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Kangaro Stapler Pins 24/6",
      category: "Stationery",
      description: "Standard stapler pin box for office use",
      purchase: 18,
      selling: 30,
      stockQty: 60,
      inWeight: false,
      weightUnit: "box",
      weight: 0,
    },
    {
      name: "Cello Butterflow Pen Pack",
      category: "Stationery",
      description: "Smooth blue ball pen value pack",
      purchase: 48,
      selling: 70,
      stockQty: 40,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "80mm Thermal Paper Roll",
      category: "Stationery",
      description: "POS billing and receipt thermal paper roll",
      purchase: 28,
      selling: 45,
      stockQty: 100,
      inWeight: false,
      weightUnit: "roll",
      weight: 0,
    },
  ],

  Medical: [
    {
      name: "Crocin Advance",
      category: "Medical",
      description: "Paracetamol 500mg fever relief",
      purchase: 28,
      selling: 42,
      stockQty: 40,
      inWeight: false,
      weightUnit: "strip",
      weight: 0,
    },
    {
      name: "Benadryl Cough Syrup",
      category: "Medical",
      description: "Dry cough relief 100ml",
      purchase: 85,
      selling: 120,
      stockQty: 18,
      inWeight: true,
      weightUnit: "ml",
      weight: 100,
    },
    {
      name: "Band-Aid Strips",
      category: "Medical",
      description: "Flexible fabric bandage strips",
      purchase: 38,
      selling: 58,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Dettol Hand Sanitizer",
      category: "Medical",
      description: "Hand sanitizer 100ml",
      purchase: 52,
      selling: 75,
      stockQty: 20,
      inWeight: true,
      weightUnit: "ml",
      weight: 100,
    },
    {
      name: "3M Surgical Mask",
      category: "Medical",
      description: "3-layer fluid resistant mask",
      purchase: 6,
      selling: 12,
      stockQty: 120,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Dr. Morepen Thermometer",
      category: "Medical",
      description: "Digital clinical thermometer",
      purchase: 145,
      selling: 210,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Omron BP Monitor",
      category: "Medical",
      description: "Automatic upper arm monitor",
      purchase: 1200,
      selling: 1650,
      stockQty: 4,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Volini Pain Relief Spray",
      category: "Medical",
      description: "Muscle pain relief spray",
      purchase: 135,
      selling: 190,
      stockQty: 15,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "ORS Electral Powder",
      category: "Medical",
      description: "Oral rehydration salts sachet",
      purchase: 12,
      selling: 20,
      stockQty: 50,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Betadine Antiseptic",
      category: "Medical",
      description: "Antiseptic wound solution",
      purchase: 75,
      selling: 110,
      stockQty: 12,
      inWeight: true,
      weightUnit: "ml",
      weight: 100,
    },
    {
      name: "Cotton Roll 500g",
      category: "Medical",
      description: "Absorbent cotton roll for first-aid use",
      purchase: 135,
      selling: 185,
      stockQty: 20,
      inWeight: true,
      weightUnit: "gram",
      weight: 500,
    },
    {
      name: "Sterile Gauze Pads",
      category: "Medical",
      description: "Sterile gauze dressing pads pack",
      purchase: 45,
      selling: 70,
      stockQty: 35,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Digital Pulse Oximeter",
      category: "Medical",
      description: "Finger pulse oxygen saturation monitor",
      purchase: 520,
      selling: 750,
      stockQty: 12,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Accu-Chek Test Strips 50",
      category: "Medical",
      description: "Blood glucose test strip pack",
      purchase: 820,
      selling: 995,
      stockQty: 10,
      inWeight: false,
      weightUnit: "box",
      weight: 0,
    },
    {
      name: "Hot Water Bag",
      category: "Medical",
      description: "Reusable rubber hot water bag",
      purchase: 145,
      selling: 220,
      stockQty: 18,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Disposable Examination Gloves",
      category: "Medical",
      description: "Single-use examination gloves box",
      purchase: 320,
      selling: 450,
      stockQty: 16,
      inWeight: false,
      weightUnit: "box",
      weight: 0,
    },
  ],

  Electronics: [
    {
      name: "Anker 20W USB-C Charger",
      category: "Electronics",
      description: "PowerIQ fast wall charger",
      purchase: 380,
      selling: 599,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "boAt Type-C Cable",
      category: "Electronics",
      description: "Tangle-free braided cable",
      purchase: 95,
      selling: 199,
      stockQty: 30,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "boAt BassHeads Earphones",
      category: "Electronics",
      description: "Extra bass wired earphones",
      purchase: 180,
      selling: 349,
      stockQty: 22,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "JBL Go 3 Speaker",
      category: "Electronics",
      description: "Portable Bluetooth speaker",
      purchase: 1200,
      selling: 1999,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Mi 10000mAh Power Bank",
      category: "Electronics",
      description: "Fast charging slim powerbank",
      purchase: 850,
      selling: 1299,
      stockQty: 6,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Zebronics USB Keyboard",
      category: "Electronics",
      description: "Multimedia wired keyboard",
      purchase: 380,
      selling: 599,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Logitech M90 Mouse",
      category: "Electronics",
      description: "Optical wired mouse",
      purchase: 280,
      selling: 449,
      stockQty: 15,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "TP-Link Wi-Fi Router",
      category: "Electronics",
      description: "Wireless Wi-Fi router",
      purchase: 850,
      selling: 1299,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Syska LED Bulb 9W",
      category: "Electronics",
      description: "Energy saving LED bulb",
      purchase: 52,
      selling: 89,
      stockQty: 40,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Havells Extension Board",
      category: "Electronics",
      description: "4 socket surge protector",
      purchase: 280,
      selling: 449,
      stockQty: 12,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "POS Thermal Printer 80mm",
      category: "Electronics",
      description: "USB thermal receipt printer for billing counters",
      purchase: 1850,
      selling: 2499,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "USB Barcode Scanner",
      category: "Electronics",
      description: "Wired barcode scanner for retail billing",
      purchase: 1250,
      selling: 1799,
      stockQty: 12,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Digital Weighing Scale 30kg",
      category: "Electronics",
      description: "Retail counter weighing scale",
      purchase: 1650,
      selling: 2299,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "UPI QR Acrylic Stand",
      category: "Electronics",
      description: "Counter stand for UPI QR payment code",
      purchase: 55,
      selling: 99,
      stockQty: 50,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "SanDisk 128GB USB Drive",
      category: "Electronics",
      description: "USB flash storage",
      purchase: 620,
      selling: 849,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Logitech K120 Keyboard",
      category: "Electronics",
      description: "Full-size wired USB keyboard",
      purchase: 480,
      selling: 699,
      stockQty: 14,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "APC 600VA UPS",
      category: "Electronics",
      description: "Backup power supply for billing computer",
      purchase: 2450,
      selling: 3199,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Havells LED Batten 20W",
      category: "Electronics",
      description: "LED tube light for shops",
      purchase: 210,
      selling: 325,
      stockQty: 30,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
  ],

  Clothing: [
    {
      name: "Jockey Cotton T-Shirt",
      category: "Clothing",
      description: "Regular fit cotton t-shirt",
      purchase: 280,
      selling: 499,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Arrow Formal Shirt",
      category: "Clothing",
      description: "Full sleeve formal shirt",
      purchase: 580,
      selling: 999,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Levi's 511 Jeans",
      category: "Clothing",
      description: "Slim fit stretch jeans",
      purchase: 1200,
      selling: 2199,
      stockQty: 16,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Biba Printed Kurti",
      category: "Clothing",
      description: "Cotton printed kurti",
      purchase: 480,
      selling: 899,
      stockQty: 12,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Jockey Leggings",
      category: "Clothing",
      description: "Cotton stretch leggings",
      purchase: 320,
      selling: 599,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Van Heusen Polo Shirt",
      category: "Clothing",
      description: "Regular fit polo shirt",
      purchase: 480,
      selling: 899,
      stockQty: 14,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Peter England Trouser",
      category: "Clothing",
      description: "Slim fit formal trouser",
      purchase: 680,
      selling: 1299,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Dollar Innerwear Vest",
      category: "Clothing",
      description: "Cotton sleeveless vest",
      purchase: 95,
      selling: 185,
      stockQty: 30,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Manyavar Cotton Kurta",
      category: "Clothing",
      description: "Classic Indian mens cotton kurta",
      purchase: 780,
      selling: 1299,
      stockQty: 14,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Libas Cotton Kurti",
      category: "Clothing",
      description: "Printed everyday cotton kurti",
      purchase: 520,
      selling: 899,
      stockQty: 18,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Saree Cotton Blend",
      category: "Clothing",
      description: "Daily-wear cotton blend Indian saree",
      purchase: 420,
      selling: 799,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "School Uniform Shirt",
      category: "Clothing",
      description: "Regular-fit school uniform shirt",
      purchase: 180,
      selling: 299,
      stockQty: 30,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Mens Cotton Track Pant",
      category: "Clothing",
      description: "Comfort-fit cotton track pant",
      purchase: 260,
      selling: 499,
      stockQty: 22,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Kids Cotton T-Shirt",
      category: "Clothing",
      description: "Round-neck cotton t-shirt for kids",
      purchase: 145,
      selling: 299,
      stockQty: 28,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
  ],

  Footwear: [
    {
      name: "Nike Revolution Running Shoes",
      category: "Footwear",
      description: "Lightweight running shoes",
      purchase: 1800,
      selling: 3299,
      stockQty: 20,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Bata Casual Sandals",
      category: "Footwear",
      description: "Comfort padded sandals",
      purchase: 480,
      selling: 899,
      stockQty: 18,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Paragon Slippers",
      category: "Footwear",
      description: "Soft rubber flip flops",
      purchase: 95,
      selling: 199,
      stockQty: 30,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Red Chief Formal Shoes",
      category: "Footwear",
      description: "Leather formal shoes",
      purchase: 1400,
      selling: 2499,
      stockQty: 12,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Liberty School Shoes",
      category: "Footwear",
      description: "Black school shoes",
      purchase: 520,
      selling: 950,
      stockQty: 15,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Adidas Adilette Slides",
      category: "Footwear",
      description: "Comfort slides",
      purchase: 680,
      selling: 1299,
      stockQty: 10,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Woodland Trekking Shoes",
      category: "Footwear",
      description: "Water resistant trekking shoes",
      purchase: 1800,
      selling: 3199,
      stockQty: 8,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Bata School Shoes",
      category: "Footwear",
      description: "Black lace-up school shoes",
      purchase: 520,
      selling: 899,
      stockQty: 20,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Sparx Sports Shoes",
      category: "Footwear",
      description: "Everyday sports shoes",
      purchase: 720,
      selling: 1199,
      stockQty: 16,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Relaxo Hawaii Slippers",
      category: "Footwear",
      description: "Daily-use rubber flip flops",
      purchase: 95,
      selling: 165,
      stockQty: 35,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Campus Running Shoes",
      category: "Footwear",
      description: "Running and walking shoes",
      purchase: 780,
      selling: 1399,
      stockQty: 14,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Ladies Flat Sandals",
      category: "Footwear",
      description: "Comfort flat sandals",
      purchase: 280,
      selling: 499,
      stockQty: 22,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Kids School Sandals",
      category: "Footwear",
      description: "Durable school sandals",
      purchase: 320,
      selling: 549,
      stockQty: 18,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
  ],

  Jewelry: [
    {
      name: "Tanishq 22K Gold Ring",
      category: "Jewelry",
      description: "22K gold finger ring",
      purchase: 22000,
      selling: 28000,
      stockQty: 5,
      inWeight: true,
      weightUnit: "gram",
      weight: 5,
    },
    {
      name: "PC Jeweller Silver Chain",
      category: "Jewelry",
      description: "Silver chain",
      purchase: 1800,
      selling: 2499,
      stockQty: 10,
      inWeight: true,
      weightUnit: "gram",
      weight: 20,
    },
    {
      name: "Mia Diamond Earrings",
      category: "Jewelry",
      description: "Diamond stud earrings",
      purchase: 18000,
      selling: 26000,
      stockQty: 4,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Tanishq Gold Necklace",
      category: "Jewelry",
      description: "Traditional gold necklace",
      purchase: 52000,
      selling: 65000,
      stockQty: 3,
      inWeight: true,
      weightUnit: "gram",
      weight: 40,
    },
    {
      name: "Shaya Silver Anklet",
      category: "Jewelry",
      description: "Sterling silver payal anklet",
      purchase: 850,
      selling: 1299,
      stockQty: 12,
      inWeight: true,
      weightUnit: "gram",
      weight: 30,
    },
    {
      name: "Zaveri Pearls Bracelet",
      category: "Jewelry",
      description: "Fashion bracelet",
      purchase: 380,
      selling: 699,
      stockQty: 15,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "925 Silver Coin 10g",
      category: "Jewelry",
      description: "Silver gifting coin",
      purchase: 900,
      selling: 1150,
      stockQty: 12,
      inWeight: true,
      weightUnit: "gram",
      weight: 10,
    },
    {
      name: "Oxidised Jhumka Earrings",
      category: "Jewelry",
      description: "Traditional oxidised fashion earrings",
      purchase: 140,
      selling: 299,
      stockQty: 25,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Kundan Necklace Set",
      category: "Jewelry",
      description: "Traditional kundan necklace set",
      purchase: 850,
      selling: 1499,
      stockQty: 10,
      inWeight: false,
      weightUnit: "set",
      weight: 0,
    },
    {
      name: "Imitation Mangalsutra",
      category: "Jewelry",
      description: "Everyday imitation mangalsutra",
      purchase: 280,
      selling: 599,
      stockQty: 18,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Silver Toe Ring Pair",
      category: "Jewelry",
      description: "Traditional bichhiya pair",
      purchase: 320,
      selling: 525,
      stockQty: 20,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Gold Plated Bangles Set",
      category: "Jewelry",
      description: "Traditional gold-plated fashion bangles",
      purchase: 420,
      selling: 799,
      stockQty: 15,
      inWeight: false,
      weightUnit: "set",
      weight: 0,
    },
  ],

  Hardware: [
    {
      name: "Stanley Claw Hammer",
      category: "Hardware",
      description: "Fibreglass handle hammer",
      purchase: 380,
      selling: 599,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Stanley Screwdriver Set",
      category: "Hardware",
      description: "Insulated screwdriver set",
      purchase: 280,
      selling: 449,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Taparia Iron Nails",
      category: "Hardware",
      description: "Iron nails pack",
      purchase: 45,
      selling: 75,
      stockQty: 50,
      inWeight: true,
      weightUnit: "kg",
      weight: 1,
    },
    {
      name: "Bosch Drill Machine",
      category: "Hardware",
      description: "Corded electric drill",
      purchase: 2200,
      selling: 3499,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Taparia Adjustable Wrench",
      category: "Hardware",
      description: "Steel adjustable wrench",
      purchase: 320,
      selling: 520,
      stockQty: 18,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Fevikwik Instant Adhesive",
      category: "Hardware",
      description: "Instant adhesive",
      purchase: 18,
      selling: 35,
      stockQty: 40,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Anchor Electrical Wire",
      category: "Hardware",
      description: "PVC electrical wire",
      purchase: 1800,
      selling: 2699,
      stockQty: 6,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Pidilite M-Seal",
      category: "Hardware",
      description: "Epoxy compound",
      purchase: 48,
      selling: 80,
      stockQty: 30,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Astral PVC Pipe 1 Inch",
      category: "Hardware",
      description: "PVC plumbing pipe",
      purchase: 185,
      selling: 260,
      stockQty: 30,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Jaquar Bib Cock",
      category: "Hardware",
      description: "Chrome plated water tap",
      purchase: 520,
      selling: 799,
      stockQty: 16,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Asian Paints Wall Putty 20kg",
      category: "Hardware",
      description: "Wall finishing putty bag",
      purchase: 640,
      selling: 760,
      stockQty: 15,
      inWeight: true,
      weightUnit: "kg",
      weight: 20,
    },
    {
      name: "Finolex Electrical Wire 90m",
      category: "Hardware",
      description: "House wiring coil",
      purchase: 1850,
      selling: 2399,
      stockQty: 10,
      inWeight: false,
      weightUnit: "coil",
      weight: 0,
    },
    {
      name: "Godrej Padlock",
      category: "Hardware",
      description: "Security padlock",
      purchase: 280,
      selling: 449,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Dr Fixit Waterproofing 1L",
      category: "Hardware",
      description: "Liquid waterproofing additive",
      purchase: 210,
      selling: 320,
      stockQty: 18,
      inWeight: true,
      weightUnit: "liter",
      weight: 1,
    },
  ],

  Furniture: [
    {
      name: "Nilkamal Plastic Chair",
      category: "Furniture",
      description: "Stackable plastic chair",
      purchase: 680,
      selling: 1099,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Durian Dining Table",
      category: "Furniture",
      description: "6-seater dining set",
      purchase: 22000,
      selling: 34999,
      stockQty: 3,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Godrej Interio Office Desk",
      category: "Furniture",
      description: "Office desk",
      purchase: 8500,
      selling: 13999,
      stockQty: 5,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Wakefit Sofa Set 3+1+1",
      category: "Furniture",
      description: "Fabric upholstered sofa set",
      purchase: 28000,
      selling: 44999,
      stockQty: 2,
      inWeight: false,
      weightUnit: "set",
      weight: 0,
    },
    {
      name: "Pepperfry Queen Bed Frame",
      category: "Furniture",
      description: "Queen bed frame",
      purchase: 18000,
      selling: 27999,
      stockQty: 3,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Godrej Interio Wardrobe",
      category: "Furniture",
      description: "Steel wardrobe",
      purchase: 12000,
      selling: 18999,
      stockQty: 4,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Nilkamal Plastic Stool",
      category: "Furniture",
      description: "Heavy-duty plastic stool",
      purchase: 280,
      selling: 449,
      stockQty: 18,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Foldable Study Table",
      category: "Furniture",
      description: "Portable foldable table",
      purchase: 850,
      selling: 1399,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Office Visitor Chair",
      category: "Furniture",
      description: "Cushioned steel-frame visitor chair",
      purchase: 1250,
      selling: 1999,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Wooden Shoe Rack",
      category: "Furniture",
      description: "Multi-shelf shoe rack",
      purchase: 1650,
      selling: 2699,
      stockQty: 6,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Single Bed Mattress",
      category: "Furniture",
      description: "Foam mattress for single bed",
      purchase: 2800,
      selling: 4499,
      stockQty: 6,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Steel Storage Rack",
      category: "Furniture",
      description: "Shop and warehouse storage rack",
      purchase: 3200,
      selling: 4999,
      stockQty: 5,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
  ],

  Cosmetic: [
    {
      name: "Lakme Face Cream",
      category: "Cosmetic",
      description: "Daily face moisturizer",
      purchase: 145,
      selling: 225,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Maybelline Lipstick",
      category: "Cosmetic",
      description: "Matte lipstick",
      purchase: 195,
      selling: 325,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Himalaya Face Wash",
      category: "Cosmetic",
      description: "Neem face wash",
      purchase: 88,
      selling: 135,
      stockQty: 18,
      inWeight: true,
      weightUnit: "ml",
      weight: 100,
    },
    {
      name: "Skinn by Titan Perfume",
      category: "Cosmetic",
      description: "Perfume 50ml",
      purchase: 580,
      selling: 995,
      stockQty: 12,
      inWeight: true,
      weightUnit: "ml",
      weight: 50,
    },
    {
      name: "Set Wet Hair Gel",
      category: "Cosmetic",
      description: "Hair styling gel",
      purchase: 95,
      selling: 155,
      stockQty: 15,
      inWeight: true,
      weightUnit: "ml",
      weight: 250,
    },
    {
      name: "L'Oreal Shampoo",
      category: "Cosmetic",
      description: "Hair shampoo",
      purchase: 165,
      selling: 265,
      stockQty: 14,
      inWeight: true,
      weightUnit: "ml",
      weight: 175,
    },
    {
      name: "Nivea Body Lotion",
      category: "Cosmetic",
      description: "Body moisturizer",
      purchase: 145,
      selling: 235,
      stockQty: 16,
      inWeight: true,
      weightUnit: "ml",
      weight: 200,
    },
    {
      name: "Dove Face Powder",
      category: "Cosmetic",
      description: "Finishing face powder",
      purchase: 185,
      selling: 299,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Lakme Sun Expert SPF 50",
      category: "Cosmetic",
      description: "Daily sunscreen lotion",
      purchase: 265,
      selling: 399,
      stockQty: 20,
      inWeight: true,
      weightUnit: "ml",
      weight: 50,
    },
    {
      name: "Mamaearth Ubtan Face Wash",
      category: "Cosmetic",
      description: "Turmeric face wash",
      purchase: 145,
      selling: 249,
      stockQty: 20,
      inWeight: true,
      weightUnit: "ml",
      weight: 100,
    },
    {
      name: "Dabur Amla Hair Oil",
      category: "Cosmetic",
      description: "Amla enriched hair oil",
      purchase: 95,
      selling: 145,
      stockQty: 25,
      inWeight: true,
      weightUnit: "ml",
      weight: 180,
    },
    {
      name: "Ponds Super Light Gel",
      category: "Cosmetic",
      description: "Hydrating face moisturizer",
      purchase: 185,
      selling: 299,
      stockQty: 18,
      inWeight: true,
      weightUnit: "gram",
      weight: 100,
    },
    {
      name: "Gillette Guard Razor Pack",
      category: "Cosmetic",
      description: "Shaving razor value pack",
      purchase: 82,
      selling: 125,
      stockQty: 30,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Vaseline Petroleum Jelly",
      category: "Cosmetic",
      description: "Skin protection petroleum jelly",
      purchase: 75,
      selling: 110,
      stockQty: 22,
      inWeight: true,
      weightUnit: "gram",
      weight: 100,
    },
  ],

  "Book Store": [
    {
      name: "Chetan Bhagat - One Indian Girl",
      category: "Book Store",
      description: "English fiction novel",
      purchase: 120,
      selling: 195,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Oxford English Dictionary",
      category: "Book Store",
      description: "Compact English dictionary",
      purchase: 380,
      selling: 599,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Arihant SSC CGL Guide",
      category: "Book Store",
      description: "SSC exam preparation guide",
      purchase: 420,
      selling: 650,
      stockQty: 14,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Panchatantra Stories",
      category: "Book Store",
      description: "Illustrated children story book",
      purchase: 95,
      selling: 160,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "NCERT Science Class 10",
      category: "Book Store",
      description: "CBSE standard textbook",
      purchase: 68,
      selling: 110,
      stockQty: 30,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "R.D. Sharma Mathematics",
      category: "Book Store",
      description: "Mathematics reference book",
      purchase: 380,
      selling: 580,
      stockQty: 12,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Classmate Notebook Pack",
      category: "Book Store",
      description: "Pack of notebooks",
      purchase: 145,
      selling: 225,
      stockQty: 20,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "NCERT Mathematics Class 10",
      category: "Book Store",
      description: "CBSE mathematics textbook",
      purchase: 78,
      selling: 120,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "NCERT Physics Class 12 Part 1",
      category: "Book Store",
      description: "CBSE physics textbook",
      purchase: 92,
      selling: 145,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Arihant JEE Main Guide",
      category: "Book Store",
      description: "Engineering entrance exam preparation guide",
      purchase: 520,
      selling: 799,
      stockQty: 12,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Oswaal CBSE Question Bank",
      category: "Book Store",
      description: "Board exam practice question bank",
      purchase: 380,
      selling: 599,
      stockQty: 16,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Indian Polity by M Laxmikanth",
      category: "Book Store",
      description: "Competitive exam Indian polity reference",
      purchase: 520,
      selling: 775,
      stockQty: 14,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "General Knowledge Year Book",
      category: "Book Store",
      description: "General knowledge reference book",
      purchase: 220,
      selling: 349,
      stockQty: 18,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
  ],

  "Mobile Shop": [
    {
      name: "Samsung Galaxy A15",
      category: "Mobile Shop",
      description: "Galaxy A-series smartphone",
      purchase: 12500,
      selling: 16999,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Spigen Mobile Cover",
      category: "Mobile Shop",
      description: "Shockproof mobile cover",
      purchase: 180,
      selling: 399,
      stockQty: 60,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Gorilla Tempered Glass",
      category: "Mobile Shop",
      description: "Screen protector",
      purchase: 45,
      selling: 149,
      stockQty: 80,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Redmi Note 13",
      category: "Mobile Shop",
      description: "Redmi Note smartphone",
      purchase: 16500,
      selling: 21999,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "boAt Airdopes 141",
      category: "Mobile Shop",
      description: "TWS wireless earbuds",
      purchase: 850,
      selling: 1499,
      stockQty: 12,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Syska 20W Fast Charger",
      category: "Mobile Shop",
      description: "Type-C fast wall charger",
      purchase: 280,
      selling: 499,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Samsung 128GB Memory Card",
      category: "Mobile Shop",
      description: "128GB microSD memory card",
      purchase: 480,
      selling: 799,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Samsung Galaxy A27 5G",
      category: "Mobile Shop",
      description: "Galaxy A-series 5G smartphone",
      purchase: 26000,
      selling: 28999,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Samsung Galaxy A57 5G",
      category: "Mobile Shop",
      description: "Galaxy A-series 5G smartphone",
      purchase: 35500,
      selling: 39999,
      stockQty: 6,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Samsung Galaxy S26 FE",
      category: "Mobile Shop",
      description: "Galaxy S-series Fan Edition smartphone",
      purchase: 51500,
      selling: 57999,
      stockQty: 5,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Apple iPhone 17 256GB",
      category: "Mobile Shop",
      description: "iPhone 17 with 256GB storage",
      purchase: 92000,
      selling: 99900,
      stockQty: 5,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "OnePlus 15 256GB",
      category: "Mobile Shop",
      description: "OnePlus flagship smartphone",
      purchase: 68000,
      selling: 73099,
      stockQty: 5,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "OnePlus Nord 6 256GB",
      category: "Mobile Shop",
      description: "Nord-series 5G smartphone",
      purchase: 36500,
      selling: 39949,
      stockQty: 7,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "REDMI 17 5G",
      category: "Mobile Shop",
      description: "REDMI 17-series 5G smartphone",
      purchase: 20500,
      selling: 23999,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "REDMI Note 17 5G",
      category: "Mobile Shop",
      description: "REDMI Note-series 5G smartphone",
      purchase: 25500,
      selling: 27999,
      stockQty: 7,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Redmi Note 15 Pro+ 5G",
      category: "Mobile Shop",
      description: "Premium Redmi Note-series smartphone",
      purchase: 35000,
      selling: 39999,
      stockQty: 6,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
  ],

  Bakery: [
    {
      name: "Britannia Bread Loaf",
      category: "Bakery",
      description: "White sandwich bread",
      purchase: 38,
      selling: 55,
      stockQty: 30,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Monginis Chocolate Cake",
      category: "Bakery",
      description: "Chocolate layer cake",
      purchase: 380,
      selling: 599,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Butter Cookies",
      category: "Bakery",
      description: "Butter cookies",
      purchase: 160,
      selling: 250,
      stockQty: 20,
      inWeight: true,
      weightUnit: "kg",
      weight: 0.5,
    },
    {
      name: "Fresh Cream Pastry",
      category: "Bakery",
      description: "Fresh cream pastry",
      purchase: 45,
      selling: 80,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Glazed Chocolate Donut",
      category: "Bakery",
      description: "Chocolate glazed donut",
      purchase: 28,
      selling: 55,
      stockQty: 30,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Croissant",
      category: "Bakery",
      description: "Buttery croissant",
      purchase: 35,
      selling: 65,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Pineapple Pastry",
      category: "Bakery",
      description: "Pineapple cream pastry",
      purchase: 42,
      selling: 75,
      stockQty: 18,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Khari Biscuit Pack",
      category: "Bakery",
      description: "Flaky savoury khari biscuits",
      purchase: 55,
      selling: 85,
      stockQty: 30,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Milk Rusk Pack",
      category: "Bakery",
      description: "Tea-time milk rusk",
      purchase: 42,
      selling: 65,
      stockQty: 35,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Pav Bread Pack",
      category: "Bakery",
      description: "Soft Indian pav bread pack",
      purchase: 28,
      selling: 45,
      stockQty: 40,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Burger Bun Pack",
      category: "Bakery",
      description: "Soft burger buns",
      purchase: 38,
      selling: 60,
      stockQty: 25,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Eggless Vanilla Cake",
      category: "Bakery",
      description: "Eggless vanilla cake",
      purchase: 320,
      selling: 525,
      stockQty: 10,
      inWeight: true,
      weightUnit: "kg",
      weight: 0.5,
    },
    {
      name: "Jeera Cookies",
      category: "Bakery",
      description: "Cumin-flavoured cookies",
      purchase: 145,
      selling: 220,
      stockQty: 20,
      inWeight: true,
      weightUnit: "gram",
      weight: 500,
    },
  ],

  Restaurant: [
    {
      name: "Punjabi Veg Thali",
      category: "Restaurant",
      description: "Dal, sabzi, roti, rice and salad",
      purchase: 95,
      selling: 180,
      stockQty: 50,
      inWeight: false,
      weightUnit: "plate",
      weight: 0,
    },
    {
      name: "Paneer Butter Masala",
      category: "Restaurant",
      description: "Paneer in tomato gravy",
      purchase: 140,
      selling: 260,
      stockQty: 30,
      inWeight: false,
      weightUnit: "plate",
      weight: 0,
    },
    {
      name: "Veg Dum Biryani",
      category: "Restaurant",
      description: "Vegetable dum biryani",
      purchase: 110,
      selling: 220,
      stockQty: 40,
      inWeight: false,
      weightUnit: "plate",
      weight: 0,
    },
    {
      name: "Butter Naan",
      category: "Restaurant",
      description: "Tandoor baked butter naan",
      purchase: 18,
      selling: 45,
      stockQty: 80,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Masala Chai",
      category: "Restaurant",
      description: "Indian masala tea",
      purchase: 8,
      selling: 20,
      stockQty: 100,
      inWeight: false,
      weightUnit: "cup",
      weight: 0,
    },
    {
      name: "Coca-Cola 300ml",
      category: "Restaurant",
      description: "Soft drink bottle",
      purchase: 22,
      selling: 45,
      stockQty: 60,
      inWeight: false,
      weightUnit: "bottle",
      weight: 0,
    },
    {
      name: "Dal Makhani",
      category: "Restaurant",
      description: "Slow cooked lentil curry",
      purchase: 120,
      selling: 230,
      stockQty: 35,
      inWeight: false,
      weightUnit: "plate",
      weight: 0,
    },
    {
      name: "Gulab Jamun",
      category: "Restaurant",
      description: "Traditional Indian sweet",
      purchase: 25,
      selling: 60,
      stockQty: 50,
      inWeight: false,
      weightUnit: "plate",
      weight: 0,
    },
    {
      name: "Gujarati Veg Thali",
      category: "Restaurant",
      description: "Dal, kadhi, sabzi, roti, rice and farsan",
      purchase: 105,
      selling: 200,
      stockQty: 40,
      inWeight: false,
      weightUnit: "plate",
      weight: 0,
    },
    {
      name: "Masala Dosa",
      category: "Restaurant",
      description: "Dosa with potato masala and chutney",
      purchase: 55,
      selling: 120,
      stockQty: 45,
      inWeight: false,
      weightUnit: "plate",
      weight: 0,
    },
    {
      name: "Chole Bhature",
      category: "Restaurant",
      description: "Chickpeas with bhature",
      purchase: 70,
      selling: 150,
      stockQty: 35,
      inWeight: false,
      weightUnit: "plate",
      weight: 0,
    },
    {
      name: "Veg Hakka Noodles",
      category: "Restaurant",
      description: "Indian-Chinese vegetable noodles",
      purchase: 75,
      selling: 160,
      stockQty: 35,
      inWeight: false,
      weightUnit: "plate",
      weight: 0,
    },
    {
      name: "Sweet Lassi",
      category: "Restaurant",
      description: "Sweet yogurt drink",
      purchase: 28,
      selling: 70,
      stockQty: 50,
      inWeight: false,
      weightUnit: "glass",
      weight: 0,
    },
    {
      name: "Idli Sambar",
      category: "Restaurant",
      description: "Idli with sambar and chutney",
      purchase: 38,
      selling: 90,
      stockQty: 50,
      inWeight: false,
      weightUnit: "plate",
      weight: 0,
    },
  ],

  "Gift Shop": [
    {
      name: "Archies Greeting Card",
      category: "Gift Shop",
      description: "Birthday greeting card",
      purchase: 28,
      selling: 60,
      stockQty: 40,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Nikon Photo Frame",
      category: "Gift Shop",
      description: "Wooden photo frame",
      purchase: 145,
      selling: 270,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Hamleys Teddy Bear",
      category: "Gift Shop",
      description: "Soft plush teddy bear",
      purchase: 280,
      selling: 499,
      stockQty: 15,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Hallmark Gift Box",
      category: "Gift Shop",
      description: "Decorative gift box",
      purchase: 80,
      selling: 160,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Engraved Metal Keychain",
      category: "Gift Shop",
      description: "Customizable steel keychain",
      purchase: 25,
      selling: 70,
      stockQty: 50,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Flower Bouquet",
      category: "Gift Shop",
      description: "Fresh mixed flower bouquet",
      purchase: 180,
      selling: 380,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Cadbury Celebration Box",
      category: "Gift Shop",
      description: "Assorted chocolate gift pack",
      purchase: 185,
      selling: 350,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Rakhi Gift Hamper",
      category: "Gift Shop",
      description: "Raksha Bandhan gift hamper",
      purchase: 280,
      selling: 549,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Diwali Dry Fruit Box",
      category: "Gift Shop",
      description: "Festive dry fruit gift box",
      purchase: 420,
      selling: 799,
      stockQty: 18,
      inWeight: false,
      weightUnit: "box",
      weight: 0,
    },
    {
      name: "Wedding Shagun Envelope Pack",
      category: "Gift Shop",
      description: "Decorative wedding envelope pack",
      purchase: 75,
      selling: 149,
      stockQty: 30,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Personalized Coffee Mug",
      category: "Gift Shop",
      description: "Custom photo coffee mug",
      purchase: 120,
      selling: 249,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "LED Decorative String Lights",
      category: "Gift Shop",
      description: "Festival decorative lights",
      purchase: 110,
      selling: 199,
      stockQty: 35,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Chocolate Gift Hamper",
      category: "Gift Shop",
      description: "Assorted chocolate hamper",
      purchase: 320,
      selling: 599,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
  ],

  "General Store": [
    {
      name: "Bharat Matches",
      category: "General Store",
      description: "Safety matchbox",
      purchase: 1,
      selling: 3,
      stockQty: 200,
      inWeight: false,
      weightUnit: "box",
      weight: 0,
    },
    {
      name: "Polybag Carry Bags",
      category: "General Store",
      description: "Grocery carry bags pack",
      purchase: 38,
      selling: 65,
      stockQty: 50,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Nilkamal Plastic Bucket",
      category: "General Store",
      description: "20L plastic bucket",
      purchase: 95,
      selling: 165,
      stockQty: 18,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Milton Steel Mug",
      category: "General Store",
      description: "Stainless steel mug",
      purchase: 55,
      selling: 110,
      stockQty: 30,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Scotch Brite Floor Broom",
      category: "General Store",
      description: "Floor sweeping broom",
      purchase: 65,
      selling: 130,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Godrej Cinthol Soap",
      category: "General Store",
      description: "Bathing soap",
      purchase: 28,
      selling: 50,
      stockQty: 40,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Vim Dish Wash Bar",
      category: "General Store",
      description: "Dish wash bar",
      purchase: 18,
      selling: 35,
      stockQty: 35,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Harpic Toilet Cleaner",
      category: "General Store",
      description: "Toilet cleaner",
      purchase: 85,
      selling: 150,
      stockQty: 15,
      inWeight: true,
      weightUnit: "ml",
      weight: 500,
    },
    {
      name: "Surf Excel Easy Wash 1kg",
      category: "General Store",
      description: "Detergent powder",
      purchase: 118,
      selling: 145,
      stockQty: 30,
      inWeight: true,
      weightUnit: "kg",
      weight: 1,
    },
    {
      name: "Lizol Floor Cleaner 1L",
      category: "General Store",
      description: "Floor cleaning liquid",
      purchase: 165,
      selling: 205,
      stockQty: 22,
      inWeight: true,
      weightUnit: "liter",
      weight: 1,
    },
    {
      name: "Good Knight Refill",
      category: "General Store",
      description: "Mosquito repellent refill",
      purchase: 62,
      selling: 85,
      stockQty: 35,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Duracell AA Battery Pack",
      category: "General Store",
      description: "AA battery multipack",
      purchase: 95,
      selling: 135,
      stockQty: 30,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Garbage Bags Large Pack",
      category: "General Store",
      description: "Household garbage bags",
      purchase: 55,
      selling: 90,
      stockQty: 40,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Surf Excel Detergent Bar",
      category: "General Store",
      description: "Laundry detergent bar",
      purchase: 18,
      selling: 25,
      stockQty: 60,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
  ],

  "Sports Shop": [
    {
      name: "SS Ton Cricket Bat",
      category: "Sports Shop",
      description: "Kashmir willow cricket bat",
      purchase: 780,
      selling: 1299,
      stockQty: 12,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "SG Cricket Ball",
      category: "Sports Shop",
      description: "Leather cricket ball",
      purchase: 145,
      selling: 260,
      stockQty: 30,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Nivia Storm Football",
      category: "Sports Shop",
      description: "Football",
      purchase: 480,
      selling: 799,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Yonex Badminton Racket",
      category: "Sports Shop",
      description: "Badminton racket",
      purchase: 380,
      selling: 650,
      stockQty: 16,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Cosco Skipping Rope",
      category: "Sports Shop",
      description: "Skipping rope",
      purchase: 75,
      selling: 149,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Adidas Sports Bag",
      category: "Sports Shop",
      description: "Gym duffel bag",
      purchase: 680,
      selling: 1199,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Nivia Volleyball",
      category: "Sports Shop",
      description: "Volleyball",
      purchase: 380,
      selling: 650,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "SG Cricket Kit Bag",
      category: "Sports Shop",
      description: "Cricket equipment bag",
      purchase: 720,
      selling: 1199,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Yonex Mavis 350 Shuttlecock",
      category: "Sports Shop",
      description: "Badminton shuttlecock tube",
      purchase: 620,
      selling: 825,
      stockQty: 15,
      inWeight: false,
      weightUnit: "tube",
      weight: 0,
    },
    {
      name: "Nivia Yoga Mat",
      category: "Sports Shop",
      description: "Exercise and yoga mat",
      purchase: 420,
      selling: 699,
      stockQty: 18,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Cosco Carrom Board",
      category: "Sports Shop",
      description: "Family size carrom board",
      purchase: 1450,
      selling: 2299,
      stockQty: 6,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Vector X Gym Gloves",
      category: "Sports Shop",
      description: "Gym training gloves",
      purchase: 220,
      selling: 399,
      stockQty: 20,
      inWeight: false,
      weightUnit: "pair",
      weight: 0,
    },
    {
      name: "Strauss Resistance Band Set",
      category: "Sports Shop",
      description: "Workout resistance bands",
      purchase: 320,
      selling: 599,
      stockQty: 16,
      inWeight: false,
      weightUnit: "set",
      weight: 0,
    },
  ],

  "Toy Shop": [
    {
      name: "Hot Wheels Toy Car",
      category: "Toy Shop",
      description: "Die-cast toy car",
      purchase: 85,
      selling: 175,
      stockQty: 40,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Barbie Fashion Doll",
      category: "Toy Shop",
      description: "Fashion doll",
      purchase: 380,
      selling: 699,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Funskool Puzzle 500pc",
      category: "Toy Shop",
      description: "500-piece puzzle",
      purchase: 195,
      selling: 380,
      stockQty: 18,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Lego Classic Blocks",
      category: "Toy Shop",
      description: "Creative building blocks",
      purchase: 580,
      selling: 1099,
      stockQty: 15,
      inWeight: false,
      weightUnit: "box",
      weight: 0,
    },
    {
      name: "Maisto RC Car",
      category: "Toy Shop",
      description: "Remote control toy car",
      purchase: 650,
      selling: 1199,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Milton Water Gun",
      category: "Toy Shop",
      description: "Toy water gun",
      purchase: 85,
      selling: 175,
      stockQty: 20,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Hamleys Board Game",
      category: "Toy Shop",
      description: "Family board game",
      purchase: 380,
      selling: 699,
      stockQty: 12,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Make in India STEM Science Kit",
      category: "Toy Shop",
      description: "Educational science activity kit",
      purchase: 280,
      selling: 499,
      stockQty: 18,
      inWeight: false,
      weightUnit: "box",
      weight: 0,
    },
    {
      name: "Wooden Learning Puzzle",
      category: "Toy Shop",
      description: "Early-learning wooden puzzle",
      purchase: 145,
      selling: 279,
      stockQty: 25,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Battery Operated Toy Train",
      category: "Toy Shop",
      description: "Battery toy train set",
      purchase: 420,
      selling: 799,
      stockQty: 14,
      inWeight: false,
      weightUnit: "set",
      weight: 0,
    },
    {
      name: "Kids Doctor Play Set",
      category: "Toy Shop",
      description: "Doctor role-play toy kit",
      purchase: 220,
      selling: 449,
      stockQty: 20,
      inWeight: false,
      weightUnit: "set",
      weight: 0,
    },
    {
      name: "Magnetic Building Blocks",
      category: "Toy Shop",
      description: "Magnetic construction block set",
      purchase: 520,
      selling: 999,
      stockQty: 12,
      inWeight: false,
      weightUnit: "box",
      weight: 0,
    },
    {
      name: "Indian Map Puzzle",
      category: "Toy Shop",
      description: "India states map puzzle",
      purchase: 120,
      selling: 249,
      stockQty: 24,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
  ],

  Agriculture: [
    {
      name: "Syngenta Wheat Seeds",
      category: "Agriculture",
      description: "Wheat seeds",
      purchase: 65,
      selling: 110,
      stockQty: 50,
      inWeight: true,
      weightUnit: "kg",
      weight: 1,
    },
    {
      name: "IFFCO Urea Fertilizer",
      category: "Agriculture",
      description: "Neem coated urea fertilizer",
      purchase: 280,
      selling: 365,
      stockQty: 30,
      inWeight: true,
      weightUnit: "kg",
      weight: 50,
    },
    {
      name: "Bayer Confidor Pesticide",
      category: "Agriculture",
      description: "Agriculture insecticide",
      purchase: 420,
      selling: 650,
      stockQty: 12,
      inWeight: true,
      weightUnit: "liter",
      weight: 1,
    },
    {
      name: "Kirloskar Water Pump",
      category: "Agriculture",
      description: "Self priming water pump",
      purchase: 5200,
      selling: 8499,
      stockQty: 5,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Falcon Steel Shovel",
      category: "Agriculture",
      description: "Steel farming shovel",
      purchase: 320,
      selling: 550,
      stockQty: 14,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Coromandel DAP Fertilizer",
      category: "Agriculture",
      description: "DAP fertilizer bag",
      purchase: 1380,
      selling: 1950,
      stockQty: 20,
      inWeight: true,
      weightUnit: "kg",
      weight: 50,
    },
    {
      name: "Mahindra Garden Sprayer",
      category: "Agriculture",
      description: "Manual knapsack sprayer",
      purchase: 850,
      selling: 1399,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Hybrid Bajra Seeds 1kg",
      category: "Agriculture",
      description: "Pearl millet seed pack",
      purchase: 180,
      selling: 240,
      stockQty: 25,
      inWeight: true,
      weightUnit: "kg",
      weight: 1,
    },
    {
      name: "Hybrid Cotton Seeds Pack",
      category: "Agriculture",
      description: "Cotton seed pack",
      purchase: 620,
      selling: 780,
      stockQty: 18,
      inWeight: false,
      weightUnit: "pack",
      weight: 0,
    },
    {
      name: "Drip Irrigation Pipe 100m",
      category: "Agriculture",
      description: "Drip irrigation pipe roll",
      purchase: 980,
      selling: 1299,
      stockQty: 10,
      inWeight: false,
      weightUnit: "roll",
      weight: 0,
    },
    {
      name: "Agriculture Tarpaulin Sheet",
      category: "Agriculture",
      description: "Farm produce cover sheet",
      purchase: 620,
      selling: 950,
      stockQty: 12,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Manual Seed Sower",
      category: "Agriculture",
      description: "Hand-operated seed sowing tool",
      purchase: 780,
      selling: 1199,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Farm Pruning Shears",
      category: "Agriculture",
      description: "Farm pruning cutter",
      purchase: 260,
      selling: 449,
      stockQty: 16,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
  ],

  Other: [
    {
      name: "Prestige Pressure Cooker",
      category: "Other",
      description: "5L pressure cooker",
      purchase: 850,
      selling: 1399,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Milton Water Bottle",
      category: "Other",
      description: "Stainless steel water bottle",
      purchase: 280,
      selling: 499,
      stockQty: 15,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Cello Tape Dispenser",
      category: "Other",
      description: "Desktop tape dispenser",
      purchase: 145,
      selling: 250,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Prestige Induction Cooktop",
      category: "Other",
      description: "Portable induction cooktop",
      purchase: 1650,
      selling: 2499,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Pigeon Mixer Grinder",
      category: "Other",
      description: "Three-jar mixer grinder",
      purchase: 1850,
      selling: 2799,
      stockQty: 8,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Milton Insulated Casserole",
      category: "Other",
      description: "Insulated casserole",
      purchase: 520,
      selling: 799,
      stockQty: 14,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Cello Food Storage Container Set",
      category: "Other",
      description: "Airtight storage container set",
      purchase: 380,
      selling: 649,
      stockQty: 18,
      inWeight: false,
      weightUnit: "set",
      weight: 0,
    },
    {
      name: "Hawkins Pressure Cooker 3L",
      category: "Other",
      description: "3L pressure cooker",
      purchase: 1150,
      selling: 1699,
      stockQty: 10,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
    {
      name: "Bajaj Dry Iron",
      category: "Other",
      description: "Household dry iron",
      purchase: 520,
      selling: 799,
      stockQty: 12,
      inWeight: false,
      weightUnit: "piece",
      weight: 0,
    },
  ],
};
